// Code generated by sqlc. DO NOT EDIT.
// source: config.sql

package db

import (
	"context"
)

const setConfig = `-- name: SetConfig :exec
INSERT INTO config(seo_title,seo_descript)values($1,$2)
`

type SetConfigParams struct {
	SeoTitle    string
	SeoDescript string
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.exec(ctx, q.setConfigStmt, setConfig, arg.SeoTitle, arg.SeoDescript)
	return err
}
