// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addNewPageStmt, err = db.PrepareContext(ctx, addNewPage); err != nil {
		return nil, fmt.Errorf("error preparing query AddNewPage: %w", err)
	}
	if q.addNewPostStmt, err = db.PrepareContext(ctx, addNewPost); err != nil {
		return nil, fmt.Errorf("error preparing query AddNewPost: %w", err)
	}
	if q.addNewUserStmt, err = db.PrepareContext(ctx, addNewUser); err != nil {
		return nil, fmt.Errorf("error preparing query AddNewUser: %w", err)
	}
	if q.disablePageStmt, err = db.PrepareContext(ctx, disablePage); err != nil {
		return nil, fmt.Errorf("error preparing query DisablePage: %w", err)
	}
	if q.disableUserStmt, err = db.PrepareContext(ctx, disableUser); err != nil {
		return nil, fmt.Errorf("error preparing query DisableUser: %w", err)
	}
	if q.enablePageStmt, err = db.PrepareContext(ctx, enablePage); err != nil {
		return nil, fmt.Errorf("error preparing query EnablePage: %w", err)
	}
	if q.enableUserStmt, err = db.PrepareContext(ctx, enableUser); err != nil {
		return nil, fmt.Errorf("error preparing query EnableUser: %w", err)
	}
	if q.getOnePostStmt, err = db.PrepareContext(ctx, getOnePost); err != nil {
		return nil, fmt.Errorf("error preparing query GetOnePost: %w", err)
	}
	if q.getOneUSerStmt, err = db.PrepareContext(ctx, getOneUSer); err != nil {
		return nil, fmt.Errorf("error preparing query GetOneUSer: %w", err)
	}
	if q.listPagesStmt, err = db.PrepareContext(ctx, listPages); err != nil {
		return nil, fmt.Errorf("error preparing query ListPages: %w", err)
	}
	if q.listPostsStmt, err = db.PrepareContext(ctx, listPosts); err != nil {
		return nil, fmt.Errorf("error preparing query ListPosts: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.setConfigStmt, err = db.PrepareContext(ctx, setConfig); err != nil {
		return nil, fmt.Errorf("error preparing query SetConfig: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addNewPageStmt != nil {
		if cerr := q.addNewPageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addNewPageStmt: %w", cerr)
		}
	}
	if q.addNewPostStmt != nil {
		if cerr := q.addNewPostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addNewPostStmt: %w", cerr)
		}
	}
	if q.addNewUserStmt != nil {
		if cerr := q.addNewUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addNewUserStmt: %w", cerr)
		}
	}
	if q.disablePageStmt != nil {
		if cerr := q.disablePageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing disablePageStmt: %w", cerr)
		}
	}
	if q.disableUserStmt != nil {
		if cerr := q.disableUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing disableUserStmt: %w", cerr)
		}
	}
	if q.enablePageStmt != nil {
		if cerr := q.enablePageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing enablePageStmt: %w", cerr)
		}
	}
	if q.enableUserStmt != nil {
		if cerr := q.enableUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing enableUserStmt: %w", cerr)
		}
	}
	if q.getOnePostStmt != nil {
		if cerr := q.getOnePostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOnePostStmt: %w", cerr)
		}
	}
	if q.getOneUSerStmt != nil {
		if cerr := q.getOneUSerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOneUSerStmt: %w", cerr)
		}
	}
	if q.listPagesStmt != nil {
		if cerr := q.listPagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPagesStmt: %w", cerr)
		}
	}
	if q.listPostsStmt != nil {
		if cerr := q.listPostsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPostsStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.setConfigStmt != nil {
		if cerr := q.setConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setConfigStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db              DBTX
	tx              *sql.Tx
	addNewPageStmt  *sql.Stmt
	addNewPostStmt  *sql.Stmt
	addNewUserStmt  *sql.Stmt
	disablePageStmt *sql.Stmt
	disableUserStmt *sql.Stmt
	enablePageStmt  *sql.Stmt
	enableUserStmt  *sql.Stmt
	getOnePostStmt  *sql.Stmt
	getOneUSerStmt  *sql.Stmt
	listPagesStmt   *sql.Stmt
	listPostsStmt   *sql.Stmt
	listUsersStmt   *sql.Stmt
	setConfigStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:              tx,
		tx:              tx,
		addNewPageStmt:  q.addNewPageStmt,
		addNewPostStmt:  q.addNewPostStmt,
		addNewUserStmt:  q.addNewUserStmt,
		disablePageStmt: q.disablePageStmt,
		disableUserStmt: q.disableUserStmt,
		enablePageStmt:  q.enablePageStmt,
		enableUserStmt:  q.enableUserStmt,
		getOnePostStmt:  q.getOnePostStmt,
		getOneUSerStmt:  q.getOneUSerStmt,
		listPagesStmt:   q.listPagesStmt,
		listPostsStmt:   q.listPostsStmt,
		listUsersStmt:   q.listUsersStmt,
		setConfigStmt:   q.setConfigStmt,
	}
}
