// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Config struct {
	SeoTitle    string
	SeoDescript string
}

type Image struct {
	ID     int32
	Name   string
	Dist   string
	Size   float64
	Width  float64
	Height float64
}

type Page struct {
	ID       int32
	Title    string
	Descr    string
	ParentID int32
	CreateAt time.Time
	IsActive bool
}

type Post struct {
	ID        int32
	Title     string
	Descr     string
	Body      string
	Thumbnail string
	Image     string
	CreateAt  time.Time
	UserID    int32
	PageID    int32
}

type User struct {
	ID       int32
	Username string
	Password string
	Email    string
	CreateAt time.Time
	IsActive bool
	IsStaff  bool
	IsAdmin  bool
}
