version: '3.3'

services:
    newsajf01:
      build:
        context: ./
        dockerfile: Dockerfile
      networks:
        - default
      # volumes:
      #   - ./app/static/docs:/app/static/docs
      expose:
        - "3000"   
      # ports: 
      #     - "80:3000"                                                                                                         
      container_name: ajf01
      hostname: ajf01
      restart: always
    

networks:  
 default:
  external:
    name: ns2020-existing-network